### ISSUE TITLE
Can't use checkbox?

### ISSUE THREAD

**Issue by ji-u** [rhapsodyn/vscode-evernote#3]
When I use "- [ ] something", I expect to get

- [x] something

However, I get the plain text "[ ] something" in evernote.

**Comment by rhapsodyn** [comment]
Trying to add some checkbox, but enml [forbid it](https://dev.evernote.com/doc/articles/enml.php) : (

Working it out.

**Comment by ji-u** [comment]
Thanks for reply!
The evernote extension for sublime could support checkbox. I'm not sure how they implement that.
In addition, they also support evernote specific html tags, add the following code could also get a checkbox. I tried it in your extension, however got error 😭 .
`<en-todo></en-todo>`
Maybe helpful for working it out.
